name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "YooByWk"
          git config user.email "tls19190@naver.com"
          git add -A .
          git commit -m "generated"
          git push https://${{ secrets.NEW_TOKEN }}@github.com/YooByWk/YooByWk.git
        env: 
          GH_TOKEN: ${{ secrets.NEW_TOKEN }}
